# .slather.yml

coverage_service: html
xcodeproj: JBSM.xcodeproj
scheme: JBSM
output_directory: ./slather
ignore:
  - "../../../../../Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/*"
  - "../../../../../Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/*"
